<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "rel_pr_ct".
 *
 * @property integer $id
 * @property integer $brand_ct_id
 * @property integer $pr_ct_id
 * @property integer $pr_access_id
 * @property integer $product_id
 * @property integer $status
 * @property integer $is_deleted
 * @property integer $created_at
 * @property integer $updated_at
 * @property integer $created_by
 * @property integer $updated_by
 *
 * @property \common\models\BrandCategories $brandCt
 * @property \common\models\ProductAccessory $prAccess
 * @property \common\models\ProductCategories $prCt
 * @property \common\models\Products $product
 * @property string $aliasModel
 */
abstract class RelPrCt extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'rel_pr_ct';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => BlameableBehavior::className(),
            ],
            [
                'class' => TimestampBehavior::className(),
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['brand_ct_id', 'pr_ct_id', 'pr_access_id', 'product_id', 'status', 'is_deleted'], 'integer'],
            [['brand_ct_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\BrandCategories::className(), 'targetAttribute' => ['brand_ct_id' => 'id']],
            [['pr_access_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\ProductAccessory::className(), 'targetAttribute' => ['pr_access_id' => 'id']],
            [['pr_ct_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\ProductCategories::className(), 'targetAttribute' => ['pr_ct_id' => 'id']],
            [['product_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\Products::className(), 'targetAttribute' => ['product_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('models', 'ID'),
            'brand_ct_id' => Yii::t('models', 'Brand Ct ID'),
            'pr_ct_id' => Yii::t('models', 'Pr Ct ID'),
            'pr_access_id' => Yii::t('models', 'Pr Access ID'),
            'product_id' => Yii::t('models', 'Product ID'),
            'status' => Yii::t('models', 'Status'),
            'is_deleted' => Yii::t('models', 'Is Deleted'),
            'created_at' => Yii::t('models', 'Created At'),
            'updated_at' => Yii::t('models', 'Updated At'),
            'created_by' => Yii::t('models', 'Created By'),
            'updated_by' => Yii::t('models', 'Updated By'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getBrandCt()
    {
        return $this->hasOne(\common\models\BrandCategories::className(), ['id' => 'brand_ct_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */

    public function getPrAccess()
    {
        return $this->hasOne(\common\models\ProductAccessory::className(), ['id' => 'pr_access_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPrCt()
    {
        return $this->hasOne(\common\models\ProductCategories::className(), ['id' => 'pr_ct_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getProduct()
    {
        return $this->hasOne(\common\models\Products::className(), ['id' => 'product_id']);
    }


    
    /**
     * @inheritdoc
     * @return \common\models\query\RelPrCt the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\query\RelPrCt(get_called_class());
    }


}
